export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE'

export const LOADING_DETAIL_MOVIE = 'LOADING_DETAIL_MOVIE'
export const GET_DETAIL_MOVIE_SUCCESS = 'GET_DETAIL_MOVIE_SECCES'
export const GET_DETAIL_MOVIE_FAILURE = 'GET_DETAIL_MOVIE_FAILURE'