export const SEARCH_MOVIE = 'SEARCH_MOVIE '

export const LOADING_SEARCH = 'LOADING_SEARCH'
export const CANCEL_SEARCH = 'CANCEL_SEARCH'
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS'
export const SEARCH_MOVIE_FAIL = 'SEARCH_MOVIE_FAIL'